version: '3.8'

services:
  videonest-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:12080:80"
    restart: unless-stopped
    # Uncomment the following if you need to set environment variables
    # environment:
    #   - NODE_ENV=production
    volumes:
      # For NGINX logs
      - ./logs:/var/log/nginx
